const translations = {
    ru: {
        logo: 'Галерея <span class="logo__highlight">улыбок</span>',
        slogan: 'Красивая улыбка начинается здесь',
        nav_about: 'О нас',
        nav_price: 'Прайс',
        nav_doctors: 'Врачи',
        nav_reviews: 'Отзывы',
        nav_booking: 'Запись',
        nav_contacts: 'Контакты',
        hero_badge: 'Самая популярная стоматология Оша',
        hero_title: 'Красивая улыбка <br />начинается <span class="highlight">здесь</span>',
        hero_subtitle: 'Современная стоматология в центре Оша. Лечение, имплантация, брекеты и эстетика — всё в одной клинике.',
        feature1: '15 видов услуг',
        feature2: '6 опытных врачей',
        feature3: 'Современное оборудование',
        feature4: 'Средние цены',
        feature5: '5000+ довольных пациентов',
        btn_book: 'Записаться',
        btn_price: 'Прейскурант',
        reviews: 'отзывов',
        why_us: 'Почему мы',
        popular_title: 'Самая популярная клиника города',
        adv_1_title: '15 услуг',
        adv_1_desc: 'Полный спектр стоматологических услуг',
        adv_2_title: 'Средние цены',
        adv_2_desc: 'Доступная стоимость без потери качества',
        adv_3_title: '6 врачей',
        adv_3_desc: 'Опытные специалисты с высшим образованием',
        adv_4_title: 'Современное оборудование',
        adv_4_desc: 'Диагностика и лечение на мировом уровне',
        adv_5_title: 'Безболезненное лечение',
        adv_5_desc: 'Современная анестезия и комфорт',
        adv_6_title: 'Высокий рейтинг',
        adv_6_desc: '4.9 на основе 5000+ отзывов',
        about_label: 'О клинике',
        about_title: 'Почему выбирают <span class="highlight">Галерею улыбок</span>',
        about_text1: '«Галерея улыбок» — это современная стоматологическая клиника в самом центре Оша. Мы предлагаем полный спектр услуг: от профессиональной чистки до сложной имплантации и ортодонтии.',
        about_text2: 'Наши врачи — специалисты с многолетним опытом, регулярно повышающие квалификацию в ведущих клиниках Европы и Азии. Мы используем только проверенные материалы и оборудование последнего поколения.',
        about_text3: 'Главный принцип — индивидуальный подход к каждому пациенту и максимальный комфорт во время лечения.',
        stat_services: 'Услуг',
        stat_doctors: 'Врачей',
        stat_patients: 'Пациентов',
        stat_rating: 'Средняя оценка',
        exp_years: '10+ лет',
        exp_market: 'на рынке Кыргызстана',
        prices_label: 'Цены',
        prices_title: 'Прейскурант <span class="highlight">цен</span>',
        cat_diagnostic: 'Консультация и диагностика',
        cat_hygiene: 'Гигиена и профилактика',
        cat_caries: 'Лечение кариеса и реставрация',
        cat_endodontics: 'Лечение корневых каналов',
        cat_prosthetics: 'Протезирование',
        cat_surgery: 'Хирургия',
        price_consult: 'Консультация с составлением плана лечения',
        price_xray: 'Рентген 1 зуба',
        price_hygiene_noair: 'Профессиональная гигиена (без Air Flow)',
        price_hygiene_air: 'Профессиональная гигиена (с Air Flow)',
        price_caries: 'Лечение кариеса зуба',
        price_restoration: 'Художественная реставрация зуба',
        price_end_1: 'Лечение 1 корневого канала',
        price_end_2: 'Лечение 2 корневого канала',
        price_end_3: 'Лечение 3 корневого канала',
        price_end_add: 'Лечение дополнительного канала',
        price_end_tool: 'Извлечение обломка инструмента из канала',
        price_end_post: 'Установка стекловолоконного (анкерный, титановый) штифта',
        price_prost_temp: 'Временная коронка (1 шт.)',
        price_prost_emax: 'Керамическая коронка (E-max, 1 шт.)',
        price_prost_metal: 'Металлокерамическая коронка (1 шт.)',
        price_prost_metal_implant: 'Металлокерамическая коронка на имплантате (1 шт.)',
        price_prost_zircon: 'Цирконовая коронка (1 шт.)',
        price_prost_denture: 'Полный съемный протез (1 челюсть)',
        price_prost_zircon_implant: 'Цирконовая коронка на имплантате (1 шт.)',
        price_surgery_extract: 'Удаление зуба',
        select: 'Выбрать',
        doctors_label: 'Врачи',
        doctors_title: 'Опытные <span class="highlight">специалисты</span>',
        doc1_spec: 'Главный врач, хирург-имплантолог',
        doc1_exp: '15 лет опыта',
        doc2_spec: 'Врач-терапевт, эндодонтист',
        doc2_exp: '12 лет опыта',
        doc3_spec: 'Ортодонт (брекеты, элайнеры)',
        doc3_exp: '10 лет опыта',
        doc4_spec: 'Детский стоматолог',
        doc4_exp: '8 лет опыта',
        doc5_spec: 'Ортопед, протезист',
        doc5_exp: '14 лет опыта',
        doc6_spec: 'Пародонтолог, гигиенист',
        doc6_exp: '9 лет опыта',
        video_label: 'Видеоотзывы',
        video_title: 'Довольные <span class="highlight">пациенты</span>',
        booking_label: 'Запись',
        booking_title: 'Запись <span class="highlight">на приём</span>',
        booking_desc: 'Заполните форму, и мы свяжемся с вами в ближайшее время для подтверждения записи.',
        label_lastname: 'Фамилия',
        label_firstname: 'Имя',
        label_phone: 'Телефон',
        label_doctor: 'Врач',
        select_doctor: 'Выберите врача',
        label_service: 'Услуга',
        select_service: 'Выберите услугу',
        label_date: 'Дата',
        label_time: 'Время',
        select_time: 'Выберите время',
        label_comment: 'Комментарий',
        contacts_label: 'Контакты',
        contacts_title: 'Свяжитесь <span class="highlight">с нами</span>',
        address: 'г. Ош, ул. Ленина 123',
        social_label: 'НАШИ СОЦ СЕТИ',
        footer_copyright: 'Галерея улыбок. Все права защищены.',
        footer_city: 'г. Ош, Кыргызстан',
        msg_fill_fields: 'Пожалуйста, заполните все обязательные поля.',
        msg_time_taken: 'Это время уже занято. Пожалуйста, выберите другое время.',
        msg_success: 'Запись успешно создана! Мы свяжемся с вами.',
        msg_error: 'Ошибка соединения с сервером. Проверьте интернет или попробуйте позже.',
    },
    ky: {
        logo: 'Галерея <span class="logo__highlight">жылмаюу</span>',
        slogan: 'Кооз жылмаюу ушул жерден башталат',
        nav_about: 'Биз жөнүндө',
        nav_price: 'Баалар',
        nav_doctors: 'Дарыгерлер',
        nav_reviews: 'Пикирлер',
        nav_booking: 'Жазылуу',
        nav_contacts: 'Байланыш',
        hero_badge: 'Оштун эң популярдуу стоматологиясы',
        hero_title: 'Кооз жылмаюу <br />ушул жерден <span class="highlight">башталат</span>',
        hero_subtitle: 'Оштун борборундагы заманбап стоматология. Дарылоо, имплантация, брекеттер жана эстетика — баары бир клиникада.',
        feature1: '15 түрдүү кызмат',
        feature2: '6 тажрыйбалуу дарыгер',
        feature3: 'Заманбап жабдуулар',
        feature4: 'Орточо баалар',
        feature5: '5000+ канааттандырылган бейтаптар',
        btn_book: 'Жазылуу',
        btn_price: 'Баа тизмеси',
        reviews: 'пикирлер',
        why_us: 'Эмне үчүн биз',
        popular_title: 'Шаардын эң популярдуу клиникасы',
        adv_1_title: '15 кызмат',
        adv_1_desc: 'Стоматологиялык кызматтардын толук спектри',
        adv_2_title: 'Орточо баалар',
        adv_2_desc: 'Сапатты жоготпостон жеткиликтүү баа',
        adv_3_title: '6 дарыгер',
        adv_3_desc: 'Жогорку билимдүү тажрыйбалуу адистер',
        adv_4_title: 'Заманбап жабдуулар',
        adv_4_desc: 'Дүйнөлүк деңгээлдеги диагностика жана дарылоо',
        adv_5_title: 'Оорусаз дарылоо',
        adv_5_desc: 'Заманбап анестезия жана ыңгайлуулук',
        adv_6_title: 'Жогорку рейтинг',
        adv_6_desc: '5000+ пикирлердин негизинде 4.9',
        about_label: 'Клиника жөнүндө',
        about_title: 'Эмне үчүн <span class="highlight">Галерея жылмаюу</span> тандашат',
        about_text1: '"Галерея жылмаюу" — Оштун борборундагы заманбап стоматологиялык клиника. Биз кесипчилик тазалоодон тарта татаал имплантация жана ортодонтияга чейинки кызматтардын толук спектрин сунуштайбыз.',
        about_text2: 'Биздин дарыгерлер — көп жылдык тажрыйбасы бар адистер, алар Европа жана Азиянын алдыңкы клиникаларында билимдерин үзгүлтүксүз жогорулатып турушат. Биз тек гана далилденген материалдарды жана акыркы муундагы жабдууларды колдонобуз.',
        about_text3: 'Негизги принцип — ар бир бейтапка жеке мамиле жана дарылоо учурунда максималдуу ыңгайлуулук.',
        stat_services: 'Кызмат',
        stat_doctors: 'Дарыгер',
        stat_patients: 'Бейтап',
        stat_rating: 'Орточо баа',
        exp_years: '10+ жыл',
        exp_market: 'Кыргызстан рыногунда',
        prices_label: 'Баалар',
        prices_title: 'Баа <span class="highlight">тизмеси</span>',
        cat_diagnostic: 'Консультация жана диагностика',
        cat_hygiene: 'Гигиена жана профилактика',
        cat_caries: 'Кариести дарылоо жана реставрация',
        cat_endodontics: 'Тамыр каналдарын дарылоо',
        cat_prosthetics: 'Протездөө',
        cat_surgery: 'Хирургия',
        price_consult: 'Дарылоо планын түзүү менен консультация',
        price_xray: '1 тиштин рентгени',
        price_hygiene_noair: 'Кесипчилик гигиена (Air Flow жок)',
        price_hygiene_air: 'Кесипчилик гигиена (Air Flow менен)',
        price_caries: 'Тиштин кариесин дарылоо',
        price_restoration: 'Тишти көркөм реставрациялоо',
        price_end_1: '1 тамыр каналын дарылоо',
        price_end_2: '2 тамыр каналын дарылоо',
        price_end_3: '3 тамыр каналын дарылоо',
        price_end_add: 'Кошумча каналды дарылоо',
        price_end_tool: 'Каналдан сынган аспапты алып салуу',
        price_end_post: 'Айнек толуктоочу (анкердик, титан) штифт орнотуу',
        price_prost_temp: 'Убактылуу коронка (1 даана)',
        price_prost_emax: 'Керамикалык коронка (E-max, 1 даана)',
        price_prost_metal: 'Металл-керамикалык коронка (1 даана)',
        price_prost_metal_implant: 'Имплантаттагы металл-керамикалык коронка (1 даана)',
        price_prost_zircon: 'Циркон коронка (1 даана)',
        price_prost_denture: 'Толук алынуучу протез (1 жаак)',
        price_prost_zircon_implant: 'Имплантаттагы циркон коронка (1 даана)',
        price_surgery_extract: 'Тишти алып салуу',
        select: 'Тандоо',
        doctors_label: 'Дарыгерлер',
        doctors_title: 'Тажрыйбалуу <span class="highlight">адистер</span>',
        doc1_spec: 'Башкы дарыгер, хирург-имплантолог',
        doc1_exp: '15 жыл тажрыйба',
        doc2_spec: 'Терапевт-дарыгер, эндодонтист',
        doc2_exp: '12 жыл тажрыйба',
        doc3_spec: 'Ортодонт (брекеттер, элайнерлер)',
        doc3_exp: '10 жыл тажрыйба',
        doc4_spec: 'Балдар стоматологу',
        doc4_exp: '8 жыл тажрыйба',
        doc5_spec: 'Ортопед, протезист',
        doc5_exp: '14 жыл тажрыйба',
        doc6_spec: 'Пародонтолог, гигиенист',
        doc6_exp: '9 жыл тажрыйба',
        video_label: 'Видео пикирлер',
        video_title: 'Канааттандырылган <span class="highlight">бейтаптар</span>',
        booking_label: 'Жазылуу',
        booking_title: 'Кабыл алууга <span class="highlight">жазылуу</span>',
        booking_desc: 'Форманы толтуруңуз, биз жакынкы арада байланышып, жазылууңузду тастыктайбыз.',
        label_lastname: 'Фамилия',
        label_firstname: 'Аты',
        label_phone: 'Телефон',
        label_doctor: 'Дарыгер',
        select_doctor: 'Дарыгерди тандаңыз',
        label_service: 'Кызмат',
        select_service: 'Кызматты тандаңыз',
        label_date: 'Күнү',
        label_time: 'Убактысы',
        select_time: 'Убакытты тандаңыз',
        label_comment: 'Комментарий',
        contacts_label: 'Байланыш',
        contacts_title: 'Биз менен <span class="highlight">байланышыңыз</span>',
        address: 'Ош шаары, Ленин көч. 123',
        social_label: 'БИЗДИН СОЦ ТАРМАКТАР',
        footer_copyright: 'Галерея жылмаюу. Бардык укуктар корголгон.',
        footer_city: 'Ош шаары, Кыргызстан',
        msg_fill_fields: 'Сураныч, бардык милдеттүү талааларды толтуруңуз.',
        msg_time_taken: 'Бул убакыт буга чейин ээлеп коюлган. Сураныч, башка убакытты тандаңыз.',
        msg_success: 'Жазылуу ийгиликтүү түзүлдү! Биз сиз менен байланышабыз.',
        msg_error: 'Серверге туташуу катасы. Интернетиңизди текшериңиз же кийин кайталап көрүңүз.',
    },
    uz: {
        logo: 'Galereya <span class="logo__highlight">tabassum</span>',
        slogan: "Go'zal tabassum shu yerda boshlanadi",
        nav_about: 'Biz haqimizda',
        nav_price: 'Narxlar',
        nav_doctors: 'Shifokorlar',
        nav_reviews: 'Sharhlar',
        nav_booking: "Yozilish",
        nav_contacts: "Aloqa",
        hero_badge: "O'shdagi eng mashhur stomatologiya",
        hero_title: "Go'zal tabassum <br />shu yerda <span class='highlight'>boshlanadi</span>",
        hero_subtitle: "O'sh markazidagi zamonaviy stomatologiya. Davolash, implantatsiya, breketlar va estetika — barchasi bitta klinikada.",
        feature1: '15 turdagi xizmat',
        feature2: '6 tajribali shifokor',
        feature3: 'Zamonaviy uskunalar',
        feature4: "O'rtacha narxlar",
        feature5: '5000+ mamnun bemorlar',
        btn_book: "Yozilish",
        btn_price: "Narxlar ro'yxati",
        reviews: 'sharhlar',
        why_us: 'Nega biz',
        popular_title: "Shaharning eng mashhur klinikasi",
        adv_1_title: '15 xizmat',
        adv_1_desc: 'Stomatologik xizmatlarning to\'liq spektri',
        adv_2_title: "O'rtacha narxlar",
        adv_2_desc: 'Sifatni yo\'qotmasdan arzon narx',
        adv_3_title: '6 shifokor',
        adv_3_desc: 'Oliy ma\'lumotli tajribali mutaxassislar',
        adv_4_title: 'Zamonaviy uskunalar',
        adv_4_desc: 'Jahon darajasidagi diagnostika va davolash',
        adv_5_title: "Og'riqsiz davolash",
        adv_5_desc: 'Zamonaviy anesteziya va qulaylik',
        adv_6_title: 'Yuqori reyting',
        adv_6_desc: '5000+ sharh asosida 4.9',
        about_label: 'Klinika haqida',
        about_title: 'Nega <span class="highlight">Galereya tabassum</span> tanlanadi',
        about_text1: '"Galereya tabassum" — O\'sh markazidagi zamonaviy stomatologik klinika. Biz professional tozalashdan tortib murakkab implantatsiya va ortodontiyagacha bo\'lgan xizmatlarning to\'liq spektrini taklif qilamiz.',
        about_text2: 'Bizning shifokorlar — ko\'p yillik tajribaga ega mutaxassislar, ular Yevropa va Osiyoning yetakchi klinikalarida bilimlarini muntazam ravishda oshirib boradilar. Biz faqat tasdiqlangan materiallar va eng so\'nggi avlod uskunalaridan foydalanamiz.',
        about_text3: 'Asosiy tamoyil — har bir bemorga individual yondashuv va davolanish vaqtida maksimal qulaylik.',
        stat_services: 'Xizmat',
        stat_doctors: 'Shifokor',
        stat_patients: 'Bemor',
        stat_rating: "O'rtacha baho",
        exp_years: '10+ yil',
        exp_market: "Qirg'iziston bozorida",
        prices_label: 'Narxlar',
        prices_title: "Narxlar <span class='highlight'>ro'yxati</span>",
        cat_diagnostic: 'Konsultatsiya va diagnostika',
        cat_hygiene: 'Gigiena va profilaktika',
        cat_caries: 'Kariesni davolash va restavratsiya',
        cat_endodontics: "Ildiz kanallarini davolash",
        cat_prosthetics: 'Protezlash',
        cat_surgery: 'Jarrohlik',
        price_consult: "Davolash rejasini tuzish bilan konsultatsiya",
        price_xray: '1 tish rentgeni',
        price_hygiene_noair: 'Professional gigiena (Air Flowsiz)',
        price_hygiene_air: 'Professional gigiena (Air Flow bilan)',
        price_caries: 'Tish kariesini davolash',
        price_restoration: "Tishni badiiy restavratsiya qilish",
        price_end_1: '1 ta ildiz kanalini davolash',
        price_end_2: '2 ta ildiz kanalini davolash',
        price_end_3: '3 ta ildiz kanalini davolash',
        price_end_add: "Qo'shimcha kanalni davolash",
        price_end_tool: "Kanaldan singan asbobni olib tashlash",
        price_end_post: 'Shisha tolali (ankr, titan) shtift o\'rnatish',
        price_prost_temp: "Vaqtinchalik koronka (1 dona)",
        price_prost_emax: 'Keramik koronka (E-max, 1 dona)',
        price_prost_metal: 'Metall-keramik koronka (1 dona)',
        price_prost_metal_implant: 'Implantatdagi metall-keramik koronka (1 dona)',
        price_prost_zircon: 'Sirkon koronka (1 dona)',
        price_prost_denture: "To'liq olinadigan protez (1 jag')",
        price_prost_zircon_implant: 'Implantatdagi sirkon koronka (1 dona)',
        price_surgery_extract: "Tishni olib tashlash",
        select: 'Tanlash',
        doctors_label: 'Shifokorlar',
        doctors_title: 'Tajribali <span class="highlight">mutaxassislar</span>',
        doc1_spec: 'Bosh shifokor, jarroh-implantolog',
        doc1_exp: '15 yil tajriba',
        doc2_spec: 'Terapevt, endodontist',
        doc2_exp: '12 yil tajriba',
        doc3_spec: 'Ortodont (breketlar, elyaynerlar)',
        doc3_exp: '10 yil tajriba',
        doc4_spec: 'Bolalar stomatologi',
        doc4_exp: '8 yil tajriba',
        doc5_spec: 'Ortoped, protezist',
        doc5_exp: '14 yil tajriba',
        doc6_spec: 'Parodontolog, gigienist',
        doc6_exp: '9 yil tajriba',
        video_label: 'Video sharhlar',
        video_title: 'Mamnun <span class="highlight">bemorlar</span>',
        booking_label: "Yozilish",
        booking_title: "Qabulga <span class='highlight'>yozilish</span>",
        booking_desc: "Formani to'ldiring, biz yaqin orada siz bilan bog'lanib, yozilishingizni tasdiqlaymiz.",
        label_lastname: 'Familiya',
        label_firstname: 'Ism',
        label_phone: 'Telefon',
        label_doctor: 'Shifokor',
        select_doctor: 'Shifokorni tanlang',
        label_service: 'Xizmat',
        select_service: 'Xizmatni tanlang',
        label_date: 'Sana',
        label_time: 'Vaqt',
        select_time: 'Vaqtni tanlang',
        label_comment: 'Izoh',
        contacts_label: "Aloqa",
        contacts_title: "Biz bilan <span class='highlight'>bog'laning</span>",
        address: "O'sh shahri, Lenin ko'ch. 123",
        social_label: "BIZNING IJTIMOIY TARMOQLAR",
        footer_copyright: 'Galereya tabassum. Barcha huquqlar himoyalangan.',
        footer_city: "O'sh, Qirg'iziston",
        msg_fill_fields: "Iltimos, barcha majburiy maydonlarni to'ldiring.",
        msg_time_taken: "Bu vaqt allaqachon band. Iltimos, boshqa vaqtni tanlang.",
        msg_success: "Yozilish muvaffaqiyatli yaratildi! Biz siz bilan bog'lanamiz.",
        msg_error: "Serverga ulanish xatosi. Internetingizni tekshiring yoki keyinroq qayta urinib ko'ring.",
    },
    en: {
        logo: 'Gallery <span class="logo__highlight">of Smiles</span>',
        slogan: 'A beautiful smile starts here',
        nav_about: 'About',
        nav_price: 'Prices',
        nav_doctors: 'Doctors',
        nav_reviews: 'Reviews',
        nav_booking: 'Booking',
        nav_contacts: 'Contacts',
        hero_badge: 'The most popular dentistry in Osh',
        hero_title: 'A beautiful smile <br />starts <span class="highlight">here</span>',
        hero_subtitle: 'Modern dentistry in the center of Osh. Treatment, implants, braces and aesthetics – all in one clinic.',
        feature1: '15 types of services',
        feature2: '6 experienced doctors',
        feature3: 'Modern equipment',
        feature4: 'Average prices',
        feature5: '5000+ satisfied patients',
        btn_book: 'Book now',
        btn_price: 'Price list',
        reviews: 'reviews',
        why_us: 'Why us',
        popular_title: 'The most popular clinic in the city',
        adv_1_title: '15 services',
        adv_1_desc: 'Full range of dental services',
        adv_2_title: 'Average prices',
        adv_2_desc: 'Affordable price without loss of quality',
        adv_3_title: '6 doctors',
        adv_3_desc: 'Experienced specialists with higher education',
        adv_4_title: 'Modern equipment',
        adv_4_desc: 'Diagnostics and treatment at the world level',
        adv_5_title: 'Painless treatment',
        adv_5_desc: 'Modern anesthesia and comfort',
        adv_6_title: 'High rating',
        adv_6_desc: '4.9 based on 5000+ reviews',
        about_label: 'About',
        about_title: 'Why choose <span class="highlight">Gallery of Smiles</span>',
        about_text1: '"Gallery of Smiles" is a modern dental clinic in the very center of Osh. We offer a full range of services: from professional cleaning to complex implantation and orthodontics.',
        about_text2: 'Our doctors are specialists with many years of experience, regularly improving their skills in leading clinics in Europe and Asia. We use only proven materials and the latest generation equipment.',
        about_text3: 'The main principle is an individual approach to each patient and maximum comfort during treatment.',
        stat_services: 'Services',
        stat_doctors: 'Doctors',
        stat_patients: 'Patients',
        stat_rating: 'Average rating',
        exp_years: '10+ years',
        exp_market: 'on the market of Kyrgyzstan',
        prices_label: 'Prices',
        prices_title: 'Price <span class="highlight">list</span>',
        cat_diagnostic: 'Consultation and diagnostics',
        cat_hygiene: 'Hygiene and prevention',
        cat_caries: 'Caries treatment and restoration',
        cat_endodontics: 'Root canal treatment',
        cat_prosthetics: 'Prosthetics',
        cat_surgery: 'Surgery',
        price_consult: 'Consultation with treatment plan',
        price_xray: 'X-ray of 1 tooth',
        price_hygiene_noair: 'Professional hygiene (without Air Flow)',
        price_hygiene_air: 'Professional hygiene (with Air Flow)',
        price_caries: 'Caries treatment of a tooth',
        price_restoration: 'Artistic tooth restoration',
        price_end_1: 'Treatment of 1 root canal',
        price_end_2: 'Treatment of 2 root canals',
        price_end_3: 'Treatment of 3 root canals',
        price_end_add: 'Treatment of an additional canal',
        price_end_tool: 'Extraction of a broken instrument from the canal',
        price_end_post: 'Installation of a fiberglass (anchor, titanium) post',
        price_prost_temp: 'Temporary crown (1 pc.)',
        price_prost_emax: 'Ceramic crown (E-max, 1 pc.)',
        price_prost_metal: 'Metal-ceramic crown (1 pc.)',
        price_prost_metal_implant: 'Metal-ceramic crown on implant (1 pc.)',
        price_prost_zircon: 'Zirconium crown (1 pc.)',
        price_prost_denture: 'Complete removable denture (1 jaw)',
        price_prost_zircon_implant: 'Zirconium crown on implant (1 pc.)',
        price_surgery_extract: 'Tooth extraction',
        select: 'Select',
        doctors_label: 'Doctors',
        doctors_title: 'Experienced <span class="highlight">specialists</span>',
        doc1_spec: 'Chief physician, surgeon-implantologist',
        doc1_exp: '15 years of experience',
        doc2_spec: 'Therapist, endodontist',
        doc2_exp: '12 years of experience',
        doc3_spec: 'Orthodontist (braces, aligners)',
        doc3_exp: '10 years of experience',
        doc4_spec: 'Pediatric dentist',
        doc4_exp: '8 years of experience',
        doc5_spec: 'Orthopedist, prosthodontist',
        doc5_exp: '14 years of experience',
        doc6_spec: 'Periodontist, hygienist',
        doc6_exp: '9 years of experience',
        video_label: 'Video reviews',
        video_title: 'Satisfied <span class="highlight">patients</span>',
        booking_label: 'Booking',
        booking_title: 'Book <span class="highlight">an appointment</span>',
        booking_desc: 'Fill out the form and we will contact you shortly to confirm your appointment.',
        label_lastname: 'Last name',
        label_firstname: 'First name',
        label_phone: 'Phone',
        label_doctor: 'Doctor',
        select_doctor: 'Select a doctor',
        label_service: 'Service',
        select_service: 'Select a service',
        label_date: 'Date',
        label_time: 'Time',
        select_time: 'Select time',
        label_comment: 'Comment',
        contacts_label: 'Contacts',
        contacts_title: 'Contact <span class="highlight">us</span>',
        address: 'Osh city, Lenin str. 123',
        social_label: 'OUR SOCIAL NETWORKS',
        footer_copyright: 'Gallery of Smiles. All rights reserved.',
        footer_city: 'Osh, Kyrgyzstan',
        msg_fill_fields: 'Please fill in all required fields.',
        msg_time_taken: 'This time is already taken. Please choose another time.',
        msg_success: 'Booking created successfully! We will contact you.',
        msg_error: 'Server connection error. Check your internet or try again later.',
    }
};

let currentLang = 'ru';

function applyLanguage(lang) {
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key] !== undefined) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') {
                el.placeholder = translations[lang][key];
            } else if (el.tagName === 'OPTION') {
                el.textContent = translations[lang][key];
            } else {
                el.innerHTML = translations[lang][key];
            }
        }
    });
    document.getElementById('langSelect').value = lang;
    localStorage.setItem('lang', lang);
    currentLang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'ru';
    applyLanguage(savedLang);
    document.getElementById('langSelect').addEventListener('change', function() {
        applyLanguage(this.value);
    });
});
