const translations = {
    ru: {
        logo: 'Галерея <span class="logo__highlight">улыбок</span>',
        slogan: 'Красивая улыбка начинается здесь',
        nav_about: 'О нас',
        nav_price: 'Прайс',
        nav_doctors: 'Врачи',
        nav_reviews: 'Отзывы',
        nav_booking: 'Запись',
        nav_contacts: 'Контакты',
        hero_badge: 'Самая популярная стоматология Оша',
        hero_title: 'Красивая улыбка <br />начинается <span class="highlight">здесь</span>',
        hero_subtitle: 'Современная стоматология в центре Оша. Лечение, имплантация, брекеты и эстетика — всё в одной клинике.',
        feature1: '15 видов услуг',
        feature2: '6 опытных врачей',
        feature3: 'Современное оборудование',
        feature4: 'Средние цены',
        feature5: '5000+ довольных пациентов',
        btn_book: 'Записаться',
        btn_price: 'Прейскурант',
        reviews: 'отзывов',
        why_us: 'Почему мы',
        popular_title: 'Самая популярная клиника города',
        adv_1_title: '15 услуг',
        adv_1_desc: 'Полный спектр стоматологических услуг',
        adv_2_title: 'Средние цены',
        adv_2_desc: 'Доступная стоимость без потери качества',
        adv_3_title: '6 врачей',
        adv_3_desc: 'Опытные специалисты с высшим образованием',
        adv_4_title: 'Современное оборудование',
        adv_4_desc: 'Диагностика и лечение на мировом уровне',
        adv_5_title: 'Безболезненное лечение',
        adv_5_desc: 'Современная анестезия и комфорт',
        adv_6_title: 'Высокий рейтинг',
        adv_6_desc: '4.9 на основе 5000+ отзывов',
        about_label: 'О клинике',
        about_title: 'Почему выбирают <span class="highlight">Галерею улыбок</span>',
        about_text1: '«Галерея улыбок» — это современная стоматологическая клиника в самом центре Оша. Мы предлагаем полный спектр услуг: от профессиональной чистки до сложной имплантации и ортодонтии.',
        about_text2: 'Наши врачи — специалисты с многолетним опытом, регулярно повышающие квалификацию в ведущих клиниках Европы и Азии. Мы используем только проверенные материалы и оборудование последнего поколения.',
        about_text3: 'Главный принцип — индивидуальный подход к каждому пациенту и максимальный комфорт во время лечения.',
        stat_services: 'Услуг',
        stat_doctors: 'Врачей',
        stat_patients: 'Пациентов',
        stat_rating: 'Средняя оценка',
        exp_years: '10+ лет',
        exp_market: 'на рынке Кыргызстана',
        prices_label: 'Цены',
        prices_title: 'Прейскурант <span class="highlight">цен</span>',
        cat_diagnostic: 'Консультация и диагностика',
        cat_hygiene: 'Гигиена и профилактика',
        cat_caries: 'Лечение кариеса и реставрация',
        cat_endodontics: 'Лечение корневых каналов',
        cat_prosthetics: 'Протезирование',
        cat_surgery: 'Хирургия',
        price_consult: 'Консультация с составлением плана лечения',
        price_xray: 'Рентген 1 зуба',
        price_hygiene_noair: 'Профессиональная гигиена (без Air Flow)',
        price_hygiene_air: 'Профессиональная гигиена (с Air Flow)',
        price_caries: 'Лечение кариеса зуба',
        price_restoration: 'Художественная реставрация зуба',
        price_end_1: 'Лечение 1 корневого канала',
        price_end_2: 'Лечение 2 корневого канала',
        price_end_3: 'Лечение 3 корневого канала',
        price_end_add: 'Лечение дополнительного канала',
        price_end_tool: 'Извлечение обломка инструмента из канала',
        price_end_post: 'Установка стекловолоконного (анкерный, титановый) штифта',
        price_prost_temp: 'Временная коронка (1 шт.)',
        price_prost_emax: 'Керамическая коронка (E-max, 1 шт.)',
        price_prost_metal: 'Металлокерамическая коронка (1 шт.)',
        price_prost_metal_implant: 'Металлокерамическая коронка на имплантате (1 шт.)',
        price_prost_zircon: 'Цирконовая коронка (1 шт.)',
        price_prost_denture: 'Полный съемный протез (1 челюсть)',
        price_prost_zircon_implant: 'Цирконовая коронка на имплантате (1 шт.)',
        price_surgery_extract: 'Удаление зуба',
        select: 'Выбрать',
        doctors_label: 'Врачи',
        doctors_title: 'Опытные <span class="highlight">специалисты</span>',
        doc1_spec: 'Главный врач, хирург-имплантолог',
        doc1_exp: '15 лет опыта',
        doc2_spec: 'Врач-терапевт, эндодонтист',
        doc2_exp: '12 лет опыта',
        doc3_spec: 'Ортодонт (брекеты, элайнеры)',
        doc3_exp: '10 лет опыта',
        doc4_spec: 'Детский стоматолог',
        doc4_exp: '8 лет опыта',
        doc5_spec: 'Ортопед, протезист',
        doc5_exp: '14 лет опыта',
        doc6_spec: 'Пародонтолог, гигиенист',
        doc6_exp: '9 лет опыта',
        video_label: 'Видеоотзывы',
        video_title: 'Довольные <span class="highlight">пациенты</span>',
        booking_label: 'Запись',
        booking_title: 'Запись <span class="highlight">на приём</span>',
        booking_desc: 'Заполните форму, и мы свяжемся с вами в ближайшее время для подтверждения записи.',
        label_lastname: 'Фамилия',
        label_firstname: 'Имя',
        label_phone: 'Телефон',
        label_doctor: 'Врач',
        select_doctor: 'Выберите врача',
        label_service: 'Услуга',
        select_service: 'Выберите услугу',
        label_date: 'Дата',
        label_time: 'Время',
        select_time: 'Выберите время',
        label_comment: 'Комментарий',
        contacts_label: 'Контакты',
        contacts_title: 'Свяжитесь <span class="highlight">с нами</span>',
        address: 'г. Ош, ул. Ленина 123',
        social_label: 'НАШИ СОЦ СЕТИ',
        footer_copyright: 'Галерея улыбок. Все права защищены.',
        footer_city: 'г. Ош, Кыргызстан',
        msg_fill_fields: 'Пожалуйста, заполните все обязательные поля.',
        msg_time_taken: 'Это время уже занято. Пожалуйста, выберите другое время.',
        msg_success: 'Запись успешно создана! Мы свяжемся с вами.',
        msg_error: 'Ошибка соединения с сервером. Проверьте интернет или попробуйте позже.',
    },
    ky: {
        // Для краткости оставляем только основные переводы, структура та же.
        // В реальном проекте нужно перевести все ключи аналогично ru.
        // Здесь приведены ключевые фразы.
        logo: 'Галерея <span class="logo__highlight">жылмаюу</span>',
        slogan: 'Кооз жылмаюу ушул жерден башталат',
        nav_about: 'Биз жөнүндө',
        nav_price: 'Баалар',
        nav_doctors: 'Дарыгерлер',
        nav_reviews: 'Пикирлер',
        nav_booking: 'Жазылуу',
        nav_contacts: 'Байланыш',
        btn_book: 'Жазылуу',
        btn_price: 'Баа тизмеси',
        hero_badge: 'Оштун эң популярдуу стоматологиясы',
        // ... остальные ключи по аналогии
    },
    uz: {
        logo: 'Galereya <span class="logo__highlight">tabassum</span>',
        slogan: 'Go\'zal tabassum shu yerda boshlanadi',
        nav_about: 'Biz haqimizda',
        nav_price: 'Narxlar',
        nav_doctors: 'Shifokorlar',
        nav_reviews: 'Sharhlar',
        nav_booking: 'Yozilish',
        nav_contacts: 'Aloqa',
        btn_book: 'Yozilish',
        btn_price: 'Narxlar ro\'yxati',
        hero_badge: "O'shdagi eng mashhur stomatologiya",
        // ...
    },
    en: {
        logo: 'Gallery <span class="logo__highlight">of Smiles</span>',
        slogan: 'A beautiful smile starts here',
        nav_about: 'About',
        nav_price: 'Prices',
        nav_doctors: 'Doctors',
        nav_reviews: 'Reviews',
        nav_booking: 'Booking',
        nav_contacts: 'Contacts',
        btn_book: 'Book now',
        btn_price: 'Price list',
        hero_badge: 'The most popular dentistry in Osh',
        hero_title: 'A beautiful smile <br />starts <span class="highlight">here</span>',
        hero_subtitle: 'Modern dentistry in the center of Osh. Treatment, implants, braces and aesthetics – all in one clinic.',
        feature1: '15 types of services',
        feature2: '6 experienced doctors',
        feature3: 'Modern equipment',
        feature4: 'Average prices',
        feature5: '5000+ satisfied patients',
        reviews: 'reviews',
        why_us: 'Why us',
        popular_title: 'The most popular clinic in the city',
        adv_1_title: '15 services',
        adv_1_desc: 'Full range of dental services',
        adv_2_title: 'Average prices',
        adv_2_desc: 'Affordable price without loss of quality',
        adv_3_title: '6 doctors',
        adv_3_desc: 'Experienced specialists with higher education',
        adv_4_title: 'Modern equipment',
        adv_4_desc: 'Diagnostics and treatment at the world level',
        adv_5_title: 'Painless treatment',
        adv_5_desc: 'Modern anesthesia and comfort',
        adv_6_title: 'High rating',
        adv_6_desc: '4.9 based on 5000+ reviews',
        about_label: 'About',
        about_title: 'Why choose <span class="highlight">Gallery of Smiles</span>',
        about_text1: '"Gallery of Smiles" is a modern dental clinic in the very center of Osh. We offer a full range of services: from professional cleaning to complex implantation and orthodontics.',
        about_text2: 'Our doctors are specialists with many years of experience, regularly improving their skills in leading clinics in Europe and Asia. We use only proven materials and the latest generation equipment.',
        about_text3: 'The main principle is an individual approach to each patient and maximum comfort during treatment.',
        stat_services: 'Services',
        stat_doctors: 'Doctors',
        stat_patients: 'Patients',
        stat_rating: 'Average rating',
        exp_years: '10+ years',
        exp_market: 'on the market of Kyrgyzstan',
        prices_label: 'Prices',
        prices_title: 'Price <span class="highlight">list</span>',
        cat_diagnostic: 'Consultation and diagnostics',
        cat_hygiene: 'Hygiene and prevention',
        cat_caries: 'Caries treatment and restoration',
        cat_endodontics: 'Root canal treatment',
        cat_prosthetics: 'Prosthetics',
        cat_surgery: 'Surgery',
        price_consult: 'Consultation with treatment plan',
        price_xray: 'X-ray of 1 tooth',
        price_hygiene_noair: 'Professional hygiene (without Air Flow)',
        price_hygiene_air: 'Professional hygiene (with Air Flow)',
        price_caries: 'Caries treatment of a tooth',
        price_restoration: 'Artistic tooth restoration',
        price_end_1: 'Treatment of 1 root canal',
        price_end_2: 'Treatment of 2 root canals',
        price_end_3: 'Treatment of 3 root canals',
        price_end_add: 'Treatment of an additional canal',
        price_end_tool: 'Extraction of a broken instrument from the canal',
        price_end_post: 'Installation of a fiberglass (anchor, titanium) post',
        price_prost_temp: 'Temporary crown (1 pc.)',
        price_prost_emax: 'Ceramic crown (E-max, 1 pc.)',
        price_prost_metal: 'Metal-ceramic crown (1 pc.)',
        price_prost_metal_implant: 'Metal-ceramic crown on implant (1 pc.)',
        price_prost_zircon: 'Zirconium crown (1 pc.)',
        price_prost_denture: 'Complete removable denture (1 jaw)',
        price_prost_zircon_implant: 'Zirconium crown on implant (1 pc.)',
        price_surgery_extract: 'Tooth extraction',
        select: 'Select',
        doctors_label: 'Doctors',
        doctors_title: 'Experienced <span class="highlight">specialists</span>',
        doc1_spec: 'Chief physician, surgeon-implantologist',
        doc1_exp: '15 years of experience',
        doc2_spec: 'Therapist, endodontist',
        doc2_exp: '12 years of experience',
        doc3_spec: 'Orthodontist (braces, aligners)',
        doc3_exp: '10 years of experience',
        doc4_spec: 'Pediatric dentist',
        doc4_exp: '8 years of experience',
        doc5_spec: 'Orthopedist, prosthodontist',
        doc5_exp: '14 years of experience',
        doc6_spec: 'Periodontist, hygienist',
        doc6_exp: '9 years of experience',
        video_label: 'Video reviews',
        video_title: 'Satisfied <span class="highlight">patients</span>',
        booking_label: 'Booking',
        booking_title: 'Book <span class="highlight">an appointment</span>',
        booking_desc: 'Fill out the form and we will contact you shortly to confirm your appointment.',
        label_lastname: 'Last name',
        label_firstname: 'First name',
        label_phone: 'Phone',
        label_doctor: 'Doctor',
        select_doctor: 'Select a doctor',
        label_service: 'Service',
        select_service: 'Select a service',
        label_date: 'Date',
        label_time: 'Time',
        select_time: 'Select time',
        label_comment: 'Comment',
        contacts_label: 'Contacts',
        contacts_title: 'Contact <span class="highlight">us</span>',
        address: 'Osh city, Lenin str. 123',
        social_label: 'OUR SOCIAL NETWORKS',
        footer_copyright: 'Gallery of Smiles. All rights reserved.',
        footer_city: 'Osh, Kyrgyzstan',
        msg_fill_fields: 'Please fill in all required fields.',
        msg_time_taken: 'This time is already taken. Please choose another time.',
        msg_success: 'Booking created successfully! We will contact you.',
        msg_error: 'Server connection error. Check your internet or try again later.',
    }
};

let currentLang = 'ru';

function applyLanguage(lang) {
    document.querySelectorAll('[data-lang]').forEach(el => {
        const key = el.getAttribute('data-lang');
        if (translations[lang] && translations[lang][key] !== undefined) {
            if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.tagName === 'SELECT') {
                el.placeholder = translations[lang][key];
            } else if (el.tagName === 'OPTION') {
                el.textContent = translations[lang][key];
            } else {
                el.innerHTML = translations[lang][key];
            }
        }
    });
    document.getElementById('langSelect').value = lang;
    localStorage.setItem('lang', lang);
    currentLang = lang;
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'ru';
    applyLanguage(savedLang);
    document.getElementById('langSelect').addEventListener('change', function() {
        applyLanguage(this.value);
    });
});
